/*
 * Copyright (c) 2025 Hubble Network, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef INCLUDE_HUBBLE_BLE_UTILS_H
#define INCLUDE_HUBBLE_BLE_UTILS_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include <hubble/ble.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Helper macros for generating Hubble BLE advertisement payloads
 *
 * These macros provide a convenient way to create BLE advertisement packets
 * that conform to the Hubble Network protocol. They handle the construction
 * of advertisement data structures including the service UUID and encrypted
 * payload data.
 *
 * #define HUBBLE_BLE_ADV_DEFINE(_name)
 *
 * @brief Define static storage for a Hubble BLE advertisement
 *
 * This macro creates static storage for advertisement data. It must be called
 * once per advertisement instance, typically at file scope.
 *
 * @param _name Unique identifier for this advertisement instance. The macro
 *              will create variables prefixed with this name.
 *
 * @note The implementation differs between platforms:
 *       - Zephyr: Creates bt_data structures for use with Zephyr's BLE API
 *       - Other platforms: Creates a raw byte buffer formatted as a BLE
 *         advertisement packet
 *
 *
 * #define HUBBLE_BLE_ADV_DATA_SET(_name, _data, _len, _out_len)
 * @brief Generate and set Hubble BLE advertisement data
 *
 * This macro generates a Hubble BLE advertisement payload from input data.
 * It encrypts the input data, adds authentication tags, and formats it
 * according to the Hubble Network protocol. The resulting payload is ready
 * to be used with the platform's BLE advertising API.
 *
 * @param _name      Name identifier used in HUBBLE_BLE_ADV_DEFINE
 * @param _data      Pointer to input data to be encrypted and advertised.
 *                   Can be NULL if input_len is 0.
 * @param _len       Length of input data in bytes
 * @param _out_len   Pointer to size_t variable:
 *                   - Input: Maximum buffer size
 *                   - Output: Length of generated advertisement data
 *
 * @return Error code from hubble_ble_advertise_get():
 *         - 0 on success
 *         - Non-zero on failure (see hubble_ble_advertise_get() documentation)
 *
 * @note This macro must be called after:
 *       - hubble_ble_init() has been called
 *       - hubble_ble_key_set() has been called
 *
 * @note The output format depends on the platform:
 *       - Zephyr: Returns number of bt_data structures (typically 2)
 *       - Other platforms: Returns total byte length of advertisement packet
 **/

#ifdef __ZEPHYR__

#include <zephyr/bluetooth/bluetooth.h>

#define HUBBLE_BLE_UTILS_BUFFER_SIZE 25

/**
 * HUBBLE_BLE_ADV_DATA_SET(_name, _data, _len, _out_len) implementation:
 *   - _name[0]: Complete List of 16-bit Service Class UUIDs
 * (BT_DATA_UUID16_ALL) Contains the Hubble UUID (2 bytes)
 *   - _name[1]: Service Data - 16-bit UUID (BT_DATA_SVC_DATA16)
 *     Contains the payload generated by hubble_ble_advertise_get()
 *   - Sets _out_len to 2 (number of bt_data entries)
 *
 * Usage:
 *   HUBBLE_BLE_ADV_DEFINE(my_adv);
 *   int err = HUBBLE_BLE_ADV_DATA_SET(my_adv, data, data_len, &out_len);
 *   bt_le_adv_start(..., my_adv, out_len, ...);
 */
#define HUBBLE_BLE_ADV_DEFINE(_name)                                           \
	static uint16_t _name##_uuid = HUBBLE_BLE_UUID;                        \
	static uint8_t _name##_adv_buf[HUBBLE_BLE_UTILS_BUFFER_SIZE] = {};     \
	static struct bt_data _name[2];

#define HUBBLE_BLE_ADV_DATA_SET(_name, _data, _len, _out_len)                  \
	({                                                                     \
		int _name##_err;                                               \
		memset(_name##_adv_buf, 0, HUBBLE_BLE_UTILS_BUFFER_SIZE);      \
		_name[0].data_len = 2;                                         \
		_name[0].type = BT_DATA_UUID16_ALL;                            \
		_name[0].data = (uint8_t *)&_name##_uuid;                      \
		*(_out_len) = HUBBLE_BLE_UTILS_BUFFER_SIZE;                    \
		_name##_err = hubble_ble_advertise_get(                        \
			_data, _len, _name##_adv_buf, _out_len);               \
		if (_name##_err == 0) {                                        \
			_name[1].data_len = *(_out_len);                       \
			_name[1].type = BT_DATA_SVC_DATA16;                    \
			_name[1].data = _name##_adv_buf;                       \
			*(_out_len) = 2;                                       \
		}                                                              \
		_name##_err;                                                   \
	})

#else

#define HUBBLE_BLE_UTILS_BUFFER_SIZE 31

/**
 * BLE advertisement packet structure:
 * Bytes 0-5: First AD structure (Complete List of 16-bit Service Class UUIDs)
 *   [0] = 0x03 (length: 3 bytes)
 *   [1] = 0x03 (AD type: Complete List of 16-bit Service Class UUIDs)
 *   [2-3] = 0xA6, 0xFC (Hubble UUID 0xFCA6 in little-endian)
 *   [4] = 0x01 (length: will be updated with service data length + 1)
 *   [5] = 0x16 (AD type: Service Data - 16-bit UUID)
 * Bytes 6+: Second AD structure (Service Data)
 *   Written by hubble_ble_advertise_get() starting at offset 6
 *
 * Usage:
 *   HUBBLE_BLE_ADV_DEFINE(my_adv);
 *   int err = HUBBLE_BLE_ADV_DATA_SET(my_adv, data, data_len, &out_len);
 *   esp_ble_gap_config_adv_data_raw(my_adv, out_len);  // ESP-IDF example
 */
#define HUBBLE_BLE_ADV_DEFINE(_name)                                           \
	static uint8_t _name[HUBBLE_BLE_UTILS_BUFFER_SIZE] = {                 \
		0x03, 0x03, 0xA6, 0xFC, 0x01, 0x16}

#define HUBBLE_BLE_ADV_DATA_SET(_name, _data, _len, _out_len)                  \
	({                                                                     \
		int _name##_err;                                               \
		memset(&_name[6], 0, HUBBLE_BLE_UTILS_BUFFER_SIZE - 6);        \
		*(_out_len) = HUBBLE_BLE_UTILS_BUFFER_SIZE - 6;                \
		_name##_err = hubble_ble_advertise_get(_data, _len, &_name[6], \
						       _out_len);              \
		if (_name##_err == 0) {                                        \
			_name[4] = *(_out_len) + 1;                            \
			*(_out_len) = *(_out_len) + 6;                         \
		}                                                              \
		_name##_err;                                                   \
	})
#endif
#ifdef __cplusplus
}
#endif

#endif /* INCLUDE_HUBBLE_BLE_UTILS_H */
