name: Trigger Docs Build

on:
  push:
    branches:
      - main

jobs:
  trigger-docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger hubble_platform_docs build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CICD_REPO_TOKEN }}
          repository: HubbleNetwork/hubble_platform_docs
          event-type: sdk-updated
          client-payload: '{"ref": "develop"}' 